trigger:
- main

stages:
- stage: Terraform
  jobs:
  - job: ApplyTerraform
    pool:
      name: Default  # 👈 Self-hosted agent pool
    steps:
    - checkout: self
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'Azure-SP-Connection'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          echo "Logging into Azure and exporting ARM environment variables for Terraform"
          
          export ARM_SUBSCRIPTION_ID=$(az account show --query id -o tsv)
          export ARM_CLIENT_ID=$(az account show --query user.name -o tsv